# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='goods',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='goods',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='rating',
            field=models.IntegerField(default=5, editable='false'),
        ),
        migrations.AddField(
            model_name='goods',
            name='rating_number',
            field=models.IntegerField(default=0, editable='false'),
        ),
        migrations.AddField(
            model_name='goods',
            name='sold_number',
            field=models.IntegerField(default=0),
        ),
    ]
