# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20160726_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
