# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_shop_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
