# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20160726_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='is_complete',
        ),
    ]
