# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 07:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20160726_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
