# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20160727_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='head_img',
            field=models.ImageField(default='photos/no_img.jpg', upload_to='img'),
        ),
    ]
