# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_customer_head_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='head_img',
        ),
    ]
