# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 06:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('content', models.TextField(max_length=300)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='isReplied',
            field=models.BooleanField(default='false'),
        ),
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='shopping.OrderForm'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='comment',
            name='goods',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shopping.Goods'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='shopping.Comment'),
        ),
    ]
