# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20160728_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, default='img/no_image.png', null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='shop',
            name='tele',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tele',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='tele',
            field=models.CharField(default='', max_length=20),
        ),
    ]
