# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_auto_20160728_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='head_img',
            field=models.ImageField(blank=True, default='img/no_image.png', null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='goods',
            name='rating_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderform',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='sold_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, default='img/no_img.jpg', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='rating_number',
            field=models.IntegerField(default=0),
        ),
    ]
