# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_auto_20160728_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='goods',
        ),
    ]
