# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_remove_comment_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='goods',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shopping.Goods'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='self_intro',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='address',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shopping.Comment'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
