# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_auto_20160728_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='isReplied',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='shopping.Comment'),
        ),
    ]
