# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_auto_20160728_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('content', models.TextField(max_length=300)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Rcontent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Rrating',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date2',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=300),
        ),
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='shopping.Comment'),
        ),
    ]
