# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0018_auto_20160728_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shopping.Comment'),
        ),
    ]
