# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='sell',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='buy',
        ),
    ]
