# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20160721_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('content', models.TextField(max_length=200)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.User')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.User')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.User')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.OrderForm'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.User'),
        ),
    ]
