# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20160721_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='order',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='seller',
            new_name='shop',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
